language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "nightly"
cache: pip
install: "pip install -e .[dev]"
script:
  coverage run --source=mlbgame setup.py test
after_success:
  coveralls
notifications:
  email: false
